events {
    worker_connections 1024;
}

http {
    # Upstream weighted traffic split for Canary Deployment
    upstream ride_service_backend {
        # Stage 1: Initial Canary (95% Blue v1 / 5% Green v2)
        server blue_service:8000 weight=95;
        server green_service:8000 weight=5;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ride_service_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Enable quick failover if backend returns error
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
        }

        location /healthz {
            proxy_pass http://ride_service_backend/healthz;
        }
    }
}
