events { worker_connections 1024; }

http {
    upstream crop_service_canary {
        # توجيه 90% من الترافيك للنسخة المستقرة و 10% لنسخة الـ Canary
        server prodml-api:8000 weight=9;
        server prodml-api-canary:8000 weight=1;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://crop_service_canary;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Request-ID $request_id;
        }

        location /health {
            proxy_pass http://crop_service_canary/health;
        }
    }
}
